name: covid
channels:
  - conda-forge
  - defaults
dependencies:
  - dash
  - flake8
  - jupyter-dash
  - geojson
  - geos
  - matplotlib
  - notebook
  - numpy
  - pandas=1.2
  - openpyxl
  - pip
  - plotly
  - pygeoif
  - pyproj
  - python=3.9.2
  - shapely
  - sqlalchemy
  - pytest
  - python-kaleido
  - unidecode
  - pip:
    - geojson-rewind
    - geomet

